language: objective-c
os: osx
stges:
    - test
    - name: deploy
      if: branch = master
jobs:
    include:
        - stage: test
          osx_image: xcode9.2
          script: echo "xcode9.2"

        - stage: test
          osx_image: xcode8.3
          script: echo "xcode8.3"

        - stage: test
          osx_image: xcode7.3
          script: echo "xcode7.3"

        - stage: test
          osx_image: xcode6.4
          script: echo "xcode6.4"
          
        - stage: deploy
          osx_image: xcode9.2
          script: echo "deploy"

